version: '3.8'
services:
  server:
    command: dlv debug --log --output="./tmp/main" --headless --listen=:2345 --api-version=2 --accept-multiclient
    ports:
      - 2345:2345
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
