version: '3.8'
services:
  client:
    build:
      args:
        NODE_ENV: production
        DEBUG:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  server:
    build:
      dockerfile: Dockerfile
