version: '3.8'
services:
  client:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      NODE_ENV: production
      DEBUG:
  server:
    build:
      dockerfile: Dockerfile
