version: '3.8'
services:
  client:
    build:
      dockerfile: dev.Dockerfile
    volumes:
      - ./client:/home/node/app
      - /home/node/app/node_modules
    environment:
      NODE_ENV: development
      DEBUG: popthegrid*
    depends_on:
      - server
    ports:
      - 35729:35729
  server:
    build:
      dockerfile: dev.Dockerfile
    volumes:
      - ./server:/server
  nginx:
    build:
      context: client/nginx
      dockerfile: Dockerfile
      args:
        DOMAIN: test.popthegrid.com
    ports:
      - 80:80
      - 443:443
    depends_on:
      - client
