version: '3.8'
services:
  client:
    build:
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - ./client:/home/node/app
      - /home/node/app/node_modules
    environment:
      NODE_ENV: development
      DEBUG: popthegrid*
  server:
    build:
      dockerfile: dev.Dockerfile
    volumes:
      - ./server:/server
