# example netlify.toml
[build]
command = "pnpm run build"
publish = "dist"

[build.environment]
GO_IMPORT_PATH = "github.com/tmaxmax/popthegrid"

[[edge_functions]]
function = "share"
path = "/*"

[[redirects]]
from = "/"
status = 200
to = "/index.html"
