# example netlify.toml
[build]
command = "pnpm run build"
functions = ".netlify/functions"
publish = "."

[build.environment]
NPM_FLAGS = "--prefix=/"

# Uncomment to use this redirect for Single Page Applications like create-react-app.
# Not needed for static site generators.
# [[redirects]]
# from = "/*"
# status = 200
# to = "/index.html"

# (optional) Settings for Netlify Dev
# https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
[dev]
command = "pnpm run dev" # Command to start your dev server
port = 3000 # Port that the dev server will be listening on
publish = "dist" # Folder with the static content for _redirect file

## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
