# example netlify.toml
[build]
command = "pnpm run build"
functions = "functions"
publish = "dist"

[build.environment]
GO_IMPORT_PATH = "github.com/tmaxmax/popthegrid"

# Uncomment to use this redirect for Single Page Applications like create-react-app.
# Not needed for static site generators.
[[redirects]]
from = "/*"
status = 200
to = "/index.html"
