# example netlify.toml
[build]
command = "pnpm run build"
publish = "dist"

[dev]
command = "pnpm run dev:client"
framework = "vite"

[build.environment]
GO_IMPORT_PATH = "github.com/tmaxmax/popthegrid"

[[redirects]]
from = "/"
status = 200
to = "/index.html"

[[headers]]
for = "/manifest.json"
[headers.values]
Content-Type = "application/manifest+json"

[[headers]]
for = "/assets/*"
[headers.values]
cache-control = '''
max-age=31536000,
immutable
'''