# example netlify.toml
[build]
command = "pnpm run build"
functions = "functions"
publish = "dist"

[build.environment]
GO_IMPORT_PATH = "github.com/tmaxmax/popthegrid"

[[redirects]]
from = "/share/*"
to = "/.netlify/functions/share/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
