# example netlify.toml
[build]
command = "pnpm run build"
publish = "dist"

[dev]
command = "pnpm run dev:client"
framework = "vite"

[build.environment]
GO_IMPORT_PATH = "github.com/tmaxmax/popthegrid"

[[redirects]]
from = "/"
status = 200
to = "/index.html"