# example netlify.toml
[build]
command = "pnpm run build"
publish = "dist"

[dev]
command = "pnpm run dev"
framework = "vite"

[build.environment]
GO_IMPORT_PATH = "github.com/tmaxmax/popthegrid"

[[edge_functions]]
function = "share"
path = "/*"

[[edge_functions]]
function = "name"
path = "/name"

[[redirects]]
from = "/"
status = 200
to = "/index.html"